# Generated by Django 4.2.2 on 2023-07-04 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0002_alter_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="country",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id_book",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viewer.book",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viewer.person",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="rating",
            name="id_book",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viewer.book",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="id_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viewer.person",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rented",
            name="id_book",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viewer.book",
            ),
        ),
        migrations.AlterField(
            model_name="rented",
            name="id_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viewer.person",
            ),
        ),
    ]
