# Generated by Django 4.2.2 on 2023-07-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0004_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="rented",
            name="returned",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name="Reserved",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_date", models.DateField(auto_now_add=True)),
                (
                    "email_sent",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "id_book",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="viewer.book",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="viewer.person",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reserved",
            },
        ),
    ]
