# Generated by Django 4.2.2 on 2023-07-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0007_alter_rented_return_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="id_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viewer.order",
            ),
        ),
    ]
