# Generated by Django 4.2.2 on 2023-07-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0008_rating_id_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
    ]
