# Generated by Django 4.2.2 on 2023-07-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0009_orderitem_canceled"),
    ]

    operations = [
        migrations.AddField(
            model_name="rented",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
    ]
