# Generated by Django 4.2.2 on 2023-08-01 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_rented_canceled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id_book', '-created']},
        ),
        migrations.AddField(
            model_name='rented',
            name='extend',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rented',
            name='id_order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.order'),
        ),
        migrations.AddField(
            model_name='rented',
            name='return_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserved',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='pay_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
